#define SSBO_BIND_CLUSTER_AABB         1
#define SSBO_BIND_CLUSTER_LIGHT_RANGE  2
#define SSBO_BIND_ALL_CLUSTER_LIGHTS   3
#define SSBO_BIND_LIGHTS               4
#define SSBO_BIND_CLUSTER_DISCOVERY    5
#define SSBO_BIND_CULL_LIGHTS_ARGS     6
#define SSBO_BIND_UNIQUE_LIGHTS_BITFIELD 7
#define SSBO_BIND_RELEVANT_LIGHTS_INDEX 8

#define SSBO_BIND_SHADOW_PARAMS        10
